# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: After Pull Request
on:
  workflow_run:
    workflows:
      - "On Pull Request"
    types:
      - completed

jobs:
  report-test-results:
    name: Report Test Results
    runs-on: ubuntu-latest
    steps:
      - name: Upload Test Results
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #v1.5.0
        with:
          artifact: csharp-tests
          name: C# Unit Test Results
          path: "*.trx"
          reporter: dotnet-trx
          fail-on-error: false
