name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Application
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ./Application
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release --filter FullyQualifiedName~UnitTests
      working-directory: ./Application
