name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Application
    - name: Build
      run: |
        ./build.ps1 -Command Build -Configuration Release
      shell: pwsh
    - name: Unit Tests
      run: |
        ./build.ps1 -Command UnitTest -Configuration Release
      shell: pwsh
