# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: 'E2E Reports'
on:
  workflow_run:
    workflows: [ 'E2E Tests' ]
    types:
      - completed

env:
  JIRA_ACCESS_TOKEN: ${{ secrets.JIRA_ACCESS_TOKEN }}
  ADMIN_APP_VERSION: '2.4.0'
  PROJECT_ID: '11900'
  CYCLE_NAME: 'Automation Cycle'
  TASK_NAME: 'Playwright Automation Task'
  FOLDER_NAME: 'Playwright Automation Run'
  RESULTS_FILE: 'playwright-results'

jobs:

  report:
    defaults:
      run:
        shell: pwsh

    runs-on: ubuntu-latest
    steps:
    - name: Send report to Zephyr
      if: github.event.workflow_run.head_branch == 'main'
      run: |
        Write-Host ${{ github.event.workflow_run.head_branch }}
        Write-Host "--- Sending test results for branch: ${{github.ref}} for event: ${{github.event_name}} ---"
