name: 'E2E Reports'
on:
  workflow_run:
    workflows: ['E2E Tests']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Generate report
      uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #v1.5.0
      with:
        artifact: test-results
        name: Playwright Tests
        path: '*.xml'
        reporter: java-junit
