name: 'Zephyr Results'
on:
  workflow_run:
    workflows: [ 'E2E Tests' ]
    types:
      - completed
    branches: [ main ]

env:
  JIRA_ACCESS_TOKEN: ${{ secrets.JIRA_ACCESS_TOKEN }}
  ADMIN_APP_VERSION: '2.3.1'
  PROJECT_ID: '11900'
  CYCLE_NAME: 'Automation Cycle'
  TASK_NAME: 'Playwright Automation Task'
  FOLDER_NAME: 'Playwright Automation Run'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
    - name: Send report to Zephyr
      run: |
        $parameters = @{
            cycleName = '${{ env.CYCLE_NAME }}'
            taskName = '${{ env.TASK_NAME }}'
            folderName = '${{ env.FOLDER_NAME }}'
        }
        .\send-test-results.ps1 -PersonalAccessToken ${{ env.JIRA_ACCESS_TOKEN }} -ProjectId ${{ env.PROJECT_ID }} -AdminAppVersion '${{ env.ADMIN_APP_VERSION }}' -ResultsFilePath '${{ env.RESULTS_FILE }}' -ConfigParams $parameters
      shell: pwsh
